### ISSUE TITLE
Issue generating types for ics721

### ISSUE THREAD

**Issue by jhernandezb** [srdtrk/go-codegen#30]
Similar to the other issue looks like it can parse array 
https://github.com/public-awesome/cw-ics721/blob/main/packages/ics721/schema/ics721.json
```
9:22AM INF Generating code to cosmwasm/types/ics721/types.go
panic: unsupported type array for definition CallbackMsg_RedeemOutgoingChannelEntries
```

```json
  {
            "description": "Redeem all entries in outgoing channel.",
            "type": "object",
            "required": ["redeem_outgoing_channel_entries"],
            "properties": {
              "redeem_outgoing_channel_entries": {
                "type": "array",
                "items": {
                  "type": "array",
                  "items": [
                    {
                      "$ref": "#/definitions/ClassId"
                    },
                    {
                      "$ref": "#/definitions/TokenId"
                    }
                  ],
                  "maxItems": 2,
                  "minItems": 2
                }
              }
            },
            "additionalProperties": false
          },
```

Would it be possible to pass a prefix when generating types? Ideally I'd like to have a single package and do something like 

```
 go-codegen generate  cosmwasm/schemas/ics721.json --prefix ICS721 --output cosmwasm/types/ics721.go --package-name  types

 go-codegen generate  cosmwasm/schemas/cw721-base.json --prefix CW271 --output cosmwasm/types/cw721.go --package-name  types
```

**Comment by srdtrk** [comment]
This issue is harder to fix since this is actually a type of wrapping I haven't considered before, see [this](https://github.com/public-awesome/cw-ics721/blob/781eeeee93233d3c6dc72d3608fb14455537d154/packages/ics721/src/msg.rs#L88). I'll try to address it this weekend. 

I don't think you should be needing a prefix, there is another solution for this in go, which is to use separate package names. [Here is an example](https://github.com/srdtrk/cw-ica-controller/tree/main/e2e/interchaintest/types) of using separate packages, where each directory contains the types for another contract. And it looks like [this in usage](https://github.com/srdtrk/cw-ica-controller/blob/d4ef6dfc0468773384538d45072d02c4a9b32def/e2e/interchaintest/contract_test.go#L74). Does this work for you?

**Comment by srdtrk** [comment]
@jhernandezb I've pushed a fix for the issue. I'm still not 100% sure that the custom Tuple types I've added will serialize/deserialize correctly. I've added some tests and json serde seems good. Feel free to create another issue if you run into json serde issues.

I'll close this issue once you acknowledge the fix or enough time passes :)

**Comment by jhernandezb** [comment]
Worked perfectly thanks! I think it would be nice to generate an http client helper  would you be open to do that, I can see if I can do a PR  but essentially we use it a lot with the grpc-web generated endpoints


```
func (c *Client) GetClassID(...) {
	type queryResponse struct {
		Response ics721.ClassId `json:"data"`
	}
	resp := &queryResponse{}
	query := ics721.QueryMsg{
		ClassId: &ics721.QueryMsg_ClassId{
			Contract: collection,
		},
	}
       err := c.SmartQuery(ctx, stargazeBridge, query, resp)
	if err != nil {
		return nil, err
	}
   ...
}

```

```
func (c *Client) SmartQuery(ctx context.Context, contract string, query any, v any) error {
	bz, err := json.Marshal(query)
	if err != nil {
		return err
	}
	q := base64.StdEncoding.EncodeToString(bz)
	queryUrl := fmt.Sprintf("%s/cosmwasm/wasm/v1/contract/%s/smart/%s", c.baseURL, contract, q)
	return c.DoRequest(ctx, queryUrl, v)
}

```

**Comment by srdtrk** [comment]
replied in https://github.com/srdtrk/go-codegen/issues/14#issuecomment-2084982181 @jhernandezb
